baseURL = "/"
title = 'Linear Programming in Practice'
enableGitInfo = true 
[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
[params]
    [params.docs]
        themeColor = "blue"
        sidebarIcons = true
        titleIcon = true
        descriptions = true
        # git info
        repoURL = "https://github.com/xianqiu/linear-programming"
        lastMod = true
        lastModRelative = true
        editPage = true
        # code color 
        prism = true
        prismTheme = "lotusdocs"

    [params.flexsearch]
    enabled = false

    [params.docsearch]
      appID     = "LOI5OKXTGT"                  
      apiKey    = "2714a64027ec87c56646114eb7d2c3b3" 
      indexName = "lpp-buypdf"                    

    [params.social]
        github = "xianqiu/linear-programming"

    [params.plausible] # Parameters for Plausible Analytics
        dataDomain = "lotusdocs.dev" # (or set via env variable HUGO_PARAMS_PLAUSIBLE_dataDomain)
        scriptURL  = "/docs/s/js/script.outbound-links.js"       # (or set via env variable HUGO_PARAMS_PLAUSIBLE_scriptURL)
        eventAPI   = "/docs/s/api/event/"       # optional - (or set via env variable HUGO_PARAMS_PLAUSIBLE_eventAPI)

[services]
  [services.googleAnalytics]
      id = 'G-PTWZS77SPR'

    